use NinjaRMM;

CREATE TABLE RMM_ROLE(
    [ID] [bigint] IDENTITY(1,1), 
    [NAME] [varchar](100) NOT NULL,	
	[STATUS] [varchar](1) NOT NULL DEFAULT 'A', 
    CONSTRAINT PK_ROLE PRIMARY KEY (ID));

		ALTER TABLE RMM_ROLE
ADD CONSTRAINT CHECK_ROLE_STATUS
  CHECK ([STATUS] IN ('A', 'I'));

ALTER TABLE RMM_ROLE ADD CONSTRAINT UNIQUE_ROLE UNIQUE ([NAME]);


CREATE TABLE RMM_CUSTOMER(
    [ID] [bigint] IDENTITY(1,1), 
    [NAME] [varchar](100) NOT NULL,
	[EMAIL] [varchar](100) NOT NULL,
	[PASSWORD] [varchar](100) NOT NULL,
	[STATUS] [varchar](1) NOT NULL DEFAULT 'A',
	[ROLE_ID] [bigint] NOT NULL ,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID),
	CONSTRAINT FK_CUSTOMER_ROLE FOREIGN KEY(ROLE_ID) REFERENCES RMM_ROLE(ID));

		ALTER TABLE RMM_CUSTOMER
ADD CONSTRAINT CHECK_CUSTOMER_STATUS
  CHECK ([STATUS] IN ('A', 'I'));

  ALTER TABLE RMM_CUSTOMER ADD CONSTRAINT UNIQUE_CUSTOMER_EMAIL UNIQUE ([EMAIL]);


CREATE TABLE RMM_DEVICE(
    [ID] [bigint] IDENTITY(1,1),
    [SYSTEM_NAME] [varchar](100) NOT NULL,
	[TYPE] [varchar](100) NOT NULL ,
	[CUSTOMER_ID] [bigint] NOT NULL ,
	[STATUS] [varchar](1) NOT NULL DEFAULT 'A',
	[START_DATE] [datetime] DEFAULT CURRENT_TIMESTAMP,
	[END_DATE] [datetime] NULL,
    CONSTRAINT PK_DEVICE PRIMARY KEY (ID),
	CONSTRAINT FK_DEVICE_CUSTOMER FOREIGN KEY(CUSTOMER_ID) REFERENCES RMM_CUSTOMER(ID));

	ALTER TABLE RMM_DEVICE
ADD CONSTRAINT CHECK_DEVICE_TYPE
  CHECK ([TYPE] IN ('WINDOWS_WORK_STATION', 'WINDOWS_SERVER', 'MAC'));

  		ALTER TABLE RMM_DEVICE
ADD CONSTRAINT CHECK_DEVICE_STATUS
  CHECK ([STATUS] IN ('A', 'I'));


  CREATE TABLE RMM_SERVICE(
    [ID] [bigint] IDENTITY(1,1),
    [NAME] [varchar](100) NOT NULL,
	[PRICE] [decimal](5,2) NOT NULL,
	[STATUS] [varchar](1) NOT NULL DEFAULT 'A', 
	[DEVICE_TYPE] [varchar](100) NOT NULL,
	CONSTRAINT PK_SERVICE PRIMARY KEY (ID)
    );

			ALTER TABLE RMM_SERVICE
ADD CONSTRAINT CHECK_SERVICE_STATUS
  CHECK ([STATUS] IN ('A', 'I'));


  ALTER TABLE RMM_SERVICE
ADD CONSTRAINT CHECK_SERVICE_DEVICE_TYPE
  CHECK ([DEVICE_TYPE] IN ('WINDOWS_WORK_STATION', 'WINDOWS_SERVER', 'MAC'));


	  CREATE TABLE RMM_CUSTOMER_SERVICE(
    [CUSTOMER_ID] [bigint] FOREIGN KEY REFERENCES RMM_CUSTOMER(ID),
	[DEVICE_ID] [bigint] FOREIGN KEY REFERENCES RMM_DEVICE(ID),
	[SERVICE_ID] [bigint] FOREIGN KEY REFERENCES RMM_SERVICE(ID),
	[STATUS] [varchar](1) NOT NULL DEFAULT 'A', 
	[START_DATE] [datetime] DEFAULT CURRENT_TIMESTAMP,
	[END_DATE] [datetime] NULL,
    CONSTRAINT PK_CUSTOMER_SERVICE PRIMARY KEY (CUSTOMER_ID,DEVICE_ID,SERVICE_ID));

				ALTER TABLE RMM_CUSTOMER_SERVICE
ADD CONSTRAINT CHECK_CUSTOMER_SERVICE_STATUS
  CHECK ([STATUS] IN ('A', 'I'));

  insert into RMM_SERVICE VALUES('ANTIVIRUS',5,'A','WINDOWS_WORK_STATION');
  insert into RMM_SERVICE VALUES('ANTIVIRUS',5,'A','WINDOWS_SERVER');
  insert into RMM_SERVICE VALUES('ANTIVIRUS',7,'A', 'MAC');
  insert into RMM_SERVICE VALUES('CLOUD_BERRY',3,'A','WINDOWS_WORK_STATION');
  insert into RMM_SERVICE VALUES('CLOUD_BERRY',3,'A','WINDOWS_SERVER');
  insert into RMM_SERVICE VALUES('CLOUD_BERRY',3,'A','MAC');
  insert into RMM_SERVICE VALUES('PSA',2,'A','WINDOWS_WORK_STATION');
  insert into RMM_SERVICE VALUES('PSA',2,'A','WINDOWS_SERVER');
  insert into RMM_SERVICE VALUES('PSA,',2,'A','MAC');
  insert into RMM_SERVICE VALUES('TEAM_VIEWER',1,'A','WINDOWS_WORK_STATION');
  insert into RMM_SERVICE VALUES('TEAM_VIEWER',1,'A','WINDOWS_SERVER');
  insert into RMM_SERVICE VALUES('TEAM_VIEWER',1,'A','MAC');
  insert into RMM_SERVICE VALUES('DEVICE',4,'A','WINDOWS_WORK_STATION');
  insert into RMM_SERVICE VALUES('DEVICE',4,'A','WINDOWS_SERVER');
  insert into RMM_SERVICE VALUES('DEVICE',4,'A','MAC');




	

  